import type { Metadata } from "next";
import { Sidebar } from "@/components/shared/sidebar";
import { Providers } from "@/components/shared/providers";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Sidebar />
        <Providers>
          <div>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
